/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.appc;

public final class R {
	public static final class anim {
		public static final int abc_fade_in = 0x7f050000;
	}
	public static final class attr {
		public static final int actionBarDivider = 0x7f010082;
	}
	public static final class styleable {
		public static final int[] AlertDialog = { 0x010100f2, 0x7f010063, 0x7f010064, 0x7f010065, 0x7f010066, 0x7f010067 };
		public static final int MenuItem_android_id = 2;
	}
}
